FROM jeffreyjflim/bb-ops.alpine AS bba

FROM gcr.io/kaniko-project/executor:debug

COPY --from=bba \
	/bin/bb \
	/scripts/vault-exec-agent.clj \
	\
	/kaniko

RUN sed -i '1s|.*|#!/kaniko/bb|' /kaniko/vault-exec-agent.clj

ENTRYPOINT ["/kaniko/vault-exec-agent.clj"]
