FROM babashka/babashka:alpine AS bba

FROM gcr.io/kaniko-project/executor:debug

COPY --from=bba /bin/bb /kaniko
COPY vault-exec-agent/vault-exec-agent.clj /kaniko

RUN sed -i '1s|.*|#!/kaniko/bb|' /kaniko/vault-exec-agent.clj

ENTRYPOINT ["/kaniko/vault-exec-agent.clj"]
