FROM jeffreyjflim/bb-ops AS bb-ops

FROM public.ecr.aws/aws-cli/aws-cli

COPY --from=bb-ops \
	\
	/usr/local/bin/bb \
	/scripts/vault-exec-agent.clj \
	\
	/usr/local/bin

RUN yum -y -q install gettext

ENTRYPOINT ["/usr/local/bin/vault-exec-agent.clj", "/usr/local/bin/aws"]
