name: |
  v-e-a/aws-cli: build+push to Docker H

on:
  push:
    branches:
      - master
    paths:
      - vault-exec-agent/*.clj
      - vault-exec-agent/Dockerfile.aws-cli
      - .github/workflows/build_push_docker_hub:_vault-exec-agent:_aws-cli.yml


jobs:
  build_and_push_docker_hub:

    runs-on: ubuntu-latest

    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push bb-ops.aws-cli
        uses: docker/build-push-action@v6
        with:
          file: vault-exec-agent/Dockerfile.aws-cli

          push: true
          sbom: true
          provenance: mode=max

          platforms: |
            linux/amd64
            linux/arm64

          tags: |
            jeffreyjflim/bb-ops.aws-cli:latest
            jeffreyjflim/bb-ops.aws-cli:${{ github.sha }}
