name: |
  p-n: build+push to Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - pipeline-notifier/gitlab2teams.clj
      - pipeline-notifier/Dockerfile
      - .github/workflows/build_push_docker_hub:_pipeline-notifier.yml


jobs:
  build_and_push_docker_hub:

    runs-on: ubuntu-latest

    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push (Docker Hub)
        uses: docker/build-push-action@v6
        with:
          file: pipeline-notifier/Dockerfile

          push: true
          sbom: true
          provenance: mode=max

          platforms: |
            linux/amd64
            linux/arm64

          tags: |
            jeffreyjflim/pipeline-notifier:latest
            jeffreyjflim/pipeline-notifier:${{ github.sha }}
